[project]
sdk_version = "0.10.0"
name = "redahm"

[entrypoint]
file_path = "assets/default.xex"
out_directory_path = "generated"
includes = [
 "redahm_config.toml"
]



setjmp_address = 0x82ff2180
longjmp_address = 0x82ff1e60


skip_lr = true
ctr_as_local = true
xer_as_local = true
cr_as_local = true
reserved_as_local = true
non_volatile_as_local = true
non_argument_as_local = true

