// Drop-in mods.
//
// A mod is a folder under mods/ (beside redahm.exe, or redahm_mods_dir). It
// holds files laid out like the game's data folder, either directly
// (mods/MyMod/KronosGame/CookedXenon/UI_FrontEnd_Loading.xxx) or under Game/
// as the TFC Installer lays mods out (mods/MyMod/Game/KronosGame/...). Files
// at a mod's top level (readmes, UPK Explorer profiles) are ignored.
//
// Every folder in mods/ gets a bool cvar, redahm_mod_<folder> (lower case,
// anything but letters and digits an underscore), off until switched on here,
// in the F4 settings or on the MODS page of the Options menu; folders whose
// names start with _ or . are not mods. The enabled mods load in the order of
// their folder names, and when two of them carry the same file the later one
// wins. The game's own files fill in the rest. A change takes effect when the
// game next starts.
//
// The runtime mounts the game data folder as one host path device, reached
// through game: and d:. Install builds one tree from the generated folder, each
// enabled mod (last listed first) and the game folder: every name comes from
// the first of them that has it, and every folder lists the files of all of
// them (the VFS opens a file by finding its folder and then the name inside
// it, and UE3 finds its packages by listing CookedXenon). A file opens as the
// real file it stands for. The tree gets a mount of its own and game: and d:
// are pointed at it; the game's own device stays mounted as it was.
//
// UE3 on the 360 takes file sizes from KronosGame\Xbox360TOC.txt ("size
// uncompressed-size 0 ..\path crc" per line) rather than from the file
// system, so a replacement whose size differs, or a file the game doesn't
// have, needs its line. The second column is non-zero for a fully compressed
// package (Engine.xxx, KronosGame.xxx...), which the game unpacks whole as it
// opens it; a replacement's comes from its own contents (0 for the
// uncompressed packages built here). The merged TOC is written to
// mods/_generated, which sits in front of every mod.
//
// A mod's game files start at the first folder, at most three levels down,
// holding KronosGame, so a mod kept in wrapper folders
// (mods/Re-Enlightened/MyMod/Game/KronosGame/...) works as it is.
//
// The first build of a mod set can take the better part of a minute. It runs
// on worker threads while this thread (the window's) keeps looking at its
// message queue, so Windows doesn't take the window for hung.
//
// Package edits (.PackagePatch files and texture packs, as the TFC Installer
// applies them) are built into mods/_generated by mod_build.cpp and served
// from there.

#include "redahm_engine/mod/mod_loader.h"

#include <algorithm>
#include <atomic>
#include <chrono>
#include <cctype>
#include <fstream>
#include <map>
#include <memory>
#include <span>
#include <sstream>
#include <string>
#include <string_view>
#include <system_error>
#include <thread>
#include <vector>

#if defined(_WIN32)
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#ifndef NOMINMAX
#define NOMINMAX
#endif
#ifndef NOGDI
#define NOGDI
#endif
#include <windows.h>
#endif

#include <rex/cvar.h>
#include <rex/hook.h>
#include <rex/ppc/func.h>
#include <rex/types.h>
#include <rex/filesystem/devices/host_path_device.h>
#include <rex/filesystem/file.h>
#include <rex/runtime.h>

#include "generated/redahm_init.h"
#include "redahm_engine/debug/crash_reporter.h"
#include "redahm_engine/mod/mod_build.h"
#include "redahm_engine/redahm_logging.h"

REXCVAR_DEFINE_STRING(redahm_mods_dir, "", "POTF/Mods",
                      "Folder holding the mods (default: mods beside redahm.exe)");

namespace redahm::mods {

namespace {

namespace fs = std::filesystem;
using rex::filesystem::Device;
using rex::filesystem::Entry;
using rex::filesystem::File;
using rex::X_STATUS;
using rex::filesystem::HostPathDevice;

constexpr std::string_view kGeneratedFolder = "_generated";
constexpr std::string_view kTocPath = "KronosGame\\Xbox360TOC.txt";
constexpr std::string_view kTocPrefix = "..\\";
constexpr std::string_view kOverlayMount = "\\Device\\RedahmMods";

fs::path g_config_dir;

// One entry of the merged tree. A folder holds the merged children of every
// layer's folder of that name; a file is the winning layer's file, which it
// opens (its reads, size and mapping are that file's).
class MergedEntry : public Entry {
 public:
  MergedEntry(Device* device, Entry* parent, std::string_view path, Entry* source)
      : Entry(device, parent, path), source_(source) {
    attributes_ = source->attributes();
    size_ = source->size();
    allocation_size_ = source->allocation_size();
    create_timestamp_ = source->create_timestamp();
    access_timestamp_ = source->access_timestamp();
    write_timestamp_ = source->write_timestamp();
  }

  void AddChild(std::unique_ptr<Entry> child) { children_.push_back(std::move(child)); }
  bool is_folder() const { return attributes_ & rex::filesystem::kFileAttributeDirectory; }

  X_STATUS Open(uint32_t desired_access, File** out_file) override {
    if (is_folder()) {
      // Listing walks this entry's (merged) children through the file.
      *out_file = new FolderFile(desired_access, this);
      return X_STATUS_SUCCESS;
    }
    return source_->Open(desired_access, out_file);
  }
  bool can_map() const override { return !is_folder() && source_->can_map(); }
  std::unique_ptr<rex::memory::MappedMemory> OpenMapped(rex::memory::MappedMemory::Mode mode,
                                                        size_t offset, size_t length) override {
    return is_folder() ? nullptr : source_->OpenMapped(mode, offset, length);
  }

 private:
  class FolderFile : public File {
   public:
    using File::File;
    void Destroy() override { delete this; }
    X_STATUS ReadSync(std::span<uint8_t>, size_t, size_t*) override {
      return X_STATUS_ACCESS_DENIED;
    }
    X_STATUS WriteSync(std::span<const uint8_t>, size_t, size_t*) override {
      return X_STATUS_ACCESS_DENIED;
    }
  };

  Entry* source_;
};

// The game's mount as one tree merged from the generated folder, the mods
// (last listed first) and last the game's own folder: every name comes from
// the first layer holding it, and a folder lists the children of that folder
// in every layer. Opening goes through the parent folder's children
// (VirtualFileSystem::OpenFile resolves the parent, then GetChild), so the
// merge has to be real folders rather than a per-path lookup.
class OverlayDevice : public Device {
 public:
  OverlayDevice(std::string_view mount_path, std::vector<std::unique_ptr<Device>> layers)
      : Device(mount_path), layers_(std::move(layers)) {}

  bool Initialize() override {
    std::vector<Entry*> roots;
    for (auto& layer : layers_) {
      if (!layer->Initialize())
        return false;
      if (Entry* root = layer->ResolvePath(""))
        roots.push_back(root);
    }
    if (roots.empty())
      return false;
    root_ = std::make_unique<MergedEntry>(this, nullptr, "", roots.back());
    Merge(*root_, roots);
    return true;
  }

  void Dump(rex::string::StringBuffer* string_buffer) override { base().Dump(string_buffer); }

  // The VFS hands over the path after the mount ("\KronosGame\..."), leading
  // separator and all; Entry::ResolvePath would take the empty part for a name.
  Entry* ResolvePath(const std::string_view path) override {
    Entry* entry = root_.get();
    size_t at = 0;
    while (entry && at <= path.size()) {
      const size_t end = std::min(path.find_first_of("\\/", at), path.size());
      if (end > at)
        entry = entry->GetChild(path.substr(at, end - at));
      at = end + 1;
    }
    return entry;
  }

  bool is_read_only() const override { return base().is_read_only(); }
  const std::string& name() const override { return base().name(); }
  uint32_t attributes() const override { return base().attributes(); }
  uint32_t component_name_max_length() const override {
    return base().component_name_max_length();
  }
  uint32_t total_allocation_units() const override { return base().total_allocation_units(); }
  uint32_t available_allocation_units() const override {
    return base().available_allocation_units();
  }
  uint32_t sectors_per_allocation_unit() const override {
    return base().sectors_per_allocation_unit();
  }
  uint32_t bytes_per_sector() const override { return base().bytes_per_sector(); }

 private:
  Device& base() const { return *layers_.back(); }

  static std::string Key(std::string_view name) {
    std::string key(name);
    std::transform(key.begin(), key.end(), key.begin(),
                   [](unsigned char c) { return char(std::tolower(c)); });
    return key;
  }

  static bool IsFolder(const Entry* e) {
    return e->attributes() & rex::filesystem::kFileAttributeDirectory;
  }

  // `folders`: the same folder in each layer that has it, first layer first.
  void Merge(MergedEntry& target, const std::vector<Entry*>& folders) {
    std::vector<std::string> order;
    std::map<std::string, std::vector<Entry*>> by_name;
    for (Entry* folder : folders) {
      for (const auto& child : folder->children()) {
        const std::string key = Key(child->name());
        auto& list = by_name[key];
        if (list.empty())
          order.push_back(key);
        list.push_back(child.get());
      }
    }
    for (const std::string& key : order) {
      const auto& list = by_name[key];
      Entry* top = list.front();
      const std::string path =
          target.path().empty() ? top->name() : target.path() + "\\" + top->name();
      auto child = std::make_unique<MergedEntry>(this, &target, path, top);
      if (IsFolder(top)) {
        std::vector<Entry*> sub;
        for (Entry* e : list) {
          if (IsFolder(e))
            sub.push_back(e);
        }
        Merge(*child, sub);
      }
      target.AddChild(std::move(child));
    }
  }

  std::vector<std::unique_ptr<Device>> layers_;
  std::unique_ptr<MergedEntry> root_;
};

std::string Lower(std::string_view text) {
  std::string out(text);
  std::transform(out.begin(), out.end(), out.begin(),
                 [](unsigned char c) { return char(std::tolower(c)); });
  return out;
}

fs::path ModsDir() {
  const std::string configured = REXCVAR_GET(redahm_mods_dir);
  if (!configured.empty()) {
    const fs::path dir(configured);
    return dir.is_absolute() ? dir : g_config_dir / dir;
  }
  return g_config_dir / "mods";
}

std::string Utf8(const fs::path& path) {
  const std::u8string text = path.u8string();
  return std::string(text.begin(), text.end());
}

// A mod folder and its cvar, registered once before the game starts. The
// cvar's setter and getter reach the value from whichever thread asks.
struct ModEntry {
  fs::path dir;
  std::string name;  // the folder's name, UTF-8
  Mod mod;
  std::shared_ptr<std::atomic<bool>> enabled;
};
std::vector<ModEntry> g_mods;

// redahm_mod_ and the folder's name in lower case, each run of anything but
// ASCII letters and digits one underscore; a number is added should that be
// empty or taken.
std::string CvarName(std::string_view folder) {
  constexpr std::string_view kPrefix = "redahm_mod_";
  std::string name(kPrefix);
  for (unsigned char c : folder) {
    if (c < 0x80 && std::isalnum(c))
      name += char(std::tolower(c));
    else if (name.back() != '_')
      name += '_';
  }
  while (name.size() > kPrefix.size() && name.back() == '_')
    name.pop_back();
  auto taken = [](const std::string& candidate) {
    return std::any_of(g_mods.begin(), g_mods.end(),
                       [&](const ModEntry& entry) { return entry.mod.cvar == candidate; }) ||
           rex::cvar::GetFlagInfo(candidate) != nullptr;
  };
  if (name.size() > kPrefix.size() && !taken(name))
    return name;
  if (name.back() != '_')
    name += '_';
  for (int number = 2;; ++number) {
    if (!taken(name + std::to_string(number)))
      return name + std::to_string(number);
  }
}

std::u16string Label(const fs::path& folder) {
  std::u16string label = folder.u16string();
  for (char16_t& c : label) {
    if (c >= u'a' && c <= u'z')
      c = char16_t(c - u'a' + u'A');
  }
  return label;
}

// A game-relative path as the game writes it (backslashes).
std::string GamePath(const fs::path& relative) {
  std::string path = relative.generic_string();
  std::replace(path.begin(), path.end(), '/', '\\');
  return path;
}

// Package edits and texture pack data: built, not served.
bool IsToolFile(const fs::path& file) {
  const std::string extension = Lower(file.extension().string());
  return extension == ".packagepatch" || extension == ".tfcmapping" || extension == ".tfc";
}

struct ModFile {
  fs::path host;
  std::string game_path;  // as found in the mod
  std::string mod;
};

// The files a mod replaces or adds, by lower-cased game path.
void CollectModFiles(const std::string& mod, const fs::path& root,
                     std::map<std::string, ModFile>& files, int& patches) {
  std::error_code error;
  for (auto it = fs::recursive_directory_iterator(root, error);
       !error && it != fs::recursive_directory_iterator(); it.increment(error)) {
    if (!it->is_regular_file())
      continue;
    const fs::path relative = fs::relative(it->path(), root, error);
    if (error || relative.parent_path().empty())
      continue;  // top-level files: readmes, tool profiles
    if (IsToolFile(relative)) {
      if (Lower(relative.extension().string()) == ".packagepatch")
        ++patches;
      continue;
    }
    const std::string game_path = GamePath(relative);
    files[Lower(game_path)] = ModFile{it->path(), game_path, mod};
  }
}

// The TOC's second column for a file: a fully compressed package's
// uncompressed size (its one compressed chunk's total), else 0.
std::string UncompressedSize(const fs::path& file) {
  std::ifstream in(file, std::ios::binary);
  unsigned char head[16] = {};
  if (!in.read(reinterpret_cast<char*>(head), sizeof(head)))
    return "0";
  auto be32 = [&](int at) {
    return uint32_t(head[at]) << 24 | uint32_t(head[at + 1]) << 16 | uint32_t(head[at + 2]) << 8 |
           head[at + 3];
  };
  const bool fully_compressed = be32(0) == 0x9E2A83C1 && be32(4) == 0x20000;
  return fully_compressed ? std::to_string(be32(12)) : "0";
}

// Where a mod's game files start: the first folder, breadth first and at most
// three levels down, holding KronosGame. The mod's own folder when there is
// none.
fs::path FindModRoot(const fs::path& dir) {
  std::vector<fs::path> level{dir};
  for (int depth = 0; depth <= 3 && !level.empty(); ++depth) {
    std::vector<fs::path> next;
    for (const fs::path& folder : level) {
      std::error_code error;
      if (fs::is_directory(folder / "KronosGame", error))
        return folder;
      for (auto it = fs::directory_iterator(folder, error);
           !error && it != fs::directory_iterator(); it.increment(error)) {
        if (it->is_directory())
          next.push_back(it->path());
      }
    }
    level = std::move(next);
  }
  return dir;
}

// The game's TOC with each replaced file's size and a line for each added one.
bool WriteToc(const fs::path& game_root, const std::map<std::string, ModFile>& files,
              const fs::path& out_path) {
  std::ifstream in(game_root / fs::path(std::string(kTocPath)), std::ios::binary);
  if (!in) {
    RDAHM_WARN("[mods] no {} in {}; file sizes left to the game", kTocPath, game_root.string());
    return false;
  }
  std::ostringstream out;
  std::map<std::string, bool> listed;
  std::string line;
  int replaced = 0;
  while (std::getline(in, line)) {
    if (!line.empty() && line.back() == '\r')
      line.pop_back();
    std::istringstream fields(line);
    std::string size, second, third, path, crc;
    if (!(fields >> size >> second >> third >> path >> crc)) {
      out << line << "\r\n";
      continue;
    }
    std::string game_path = path;
    if (game_path.rfind(kTocPrefix, 0) == 0)
      game_path.erase(0, kTocPrefix.size());
    const std::string key = Lower(game_path);
    listed[key] = true;
    if (auto it = files.find(key); it != files.end()) {
      std::error_code error;
      const auto new_size = fs::file_size(it->second.host, error);
      if (!error) {
        size = std::to_string(new_size);
        second = UncompressedSize(it->second.host);
        ++replaced;
      }
    }
    out << size << ' ' << second << ' ' << third << ' ' << path << ' ' << crc << "\r\n";
  }
  int added = 0;
  for (const auto& [key, file] : files) {
    if (listed.count(key) || key == Lower(kTocPath))
      continue;
    std::error_code error;
    const auto size = fs::file_size(file.host, error);
    if (error)
      continue;
    out << size << ' ' << UncompressedSize(file.host) << " 0 " << kTocPrefix << file.game_path
        << " 0\r\n";
    ++added;
  }
  fs::create_directories(out_path.parent_path());
  std::ofstream toc(out_path, std::ios::binary | std::ios::trunc);
  toc << out.str();
  RDAHM_INFO("[mods] TOC: {} sizes updated, {} files added", replaced, added);
  return bool(toc);
}

// game:'s device: the runtime mounts the game data folder as a host path
// device and links game: and d: to it.
HostPathDevice* GameDevice(rex::filesystem::VirtualFileSystem* vfs) {
  for (std::string_view link : {"game:", "game:\\", "d:", "d:\\"}) {
    if (Entry* entry = vfs->ResolvePath(link)) {
      if (auto* device = dynamic_cast<HostPathDevice*>(entry->device()))
        return device;
    }
  }
  return nullptr;
}

}  // namespace

void SetConfigPath(const fs::path& config_path) {
  g_config_dir = config_path.parent_path();
}

void RegisterModCvars() {
  if (!g_mods.empty())
    return;
  const fs::path mods_dir = ModsDir();
  std::vector<fs::path> folders;
  std::error_code error;
  for (auto it = fs::directory_iterator(mods_dir, error);
       !error && it != fs::directory_iterator(); it.increment(error)) {
    const std::string name = Utf8(it->path().filename());
    if (it->is_directory() && !name.empty() && name[0] != '_' && name[0] != '.')
      folders.push_back(it->path());
  }
  std::sort(folders.begin(), folders.end(), [](const fs::path& a, const fs::path& b) {
    return Lower(Utf8(a.filename())) < Lower(Utf8(b.filename()));
  });
  for (const fs::path& dir : folders) {
    ModEntry entry;
    entry.dir = dir;
    entry.name = Utf8(dir.filename());
    entry.mod.label = Label(dir.filename());
    entry.mod.cvar = CvarName(entry.name);
    entry.enabled = std::make_shared<std::atomic<bool>>(false);
    rex::cvar::FlagEntry flag;
    flag.name = entry.mod.cvar;
    flag.type = rex::cvar::FlagType::Boolean;
    flag.category = "POTF/Mods";
    flag.description = "Load the mod in mods/" + entry.name;
    flag.setter = [value = entry.enabled](std::string_view text) {
      value->store(rex::string::from_string<bool>(text, false));
      return true;
    };
    flag.getter = [value = entry.enabled] { return std::string(value->load() ? "true" : "false"); };
    flag.command_callback = [](std::string_view) {};
    flag.lifecycle = rex::cvar::Lifecycle::kRequiresRestart;
    flag.default_value = "false";
    // Registering replays the config's value, loaded before the cvar existed.
    if (!rex::cvar::RegisterFlag(std::move(flag)))
      continue;
    RDAHM_INFO("[mods] '{}': {} = {}", entry.name, entry.mod.cvar,
               entry.enabled->load() ? "true" : "false");
    g_mods.push_back(std::move(entry));
  }
  if (g_mods.empty())
    RDAHM_INFO("[mods] no mods in {}", Utf8(mods_dir));
}

std::vector<Mod> Mods() {
  std::vector<Mod> mods;
  for (const ModEntry& entry : g_mods)
    mods.push_back(entry.mod);
  return mods;
}

void Install(rex::Runtime* runtime) {
  std::vector<ModEntry*> mods;
  for (ModEntry& entry : g_mods) {
    if (entry.enabled->load())
      mods.push_back(&entry);
  }
  if (mods.empty() || !runtime || !runtime->file_system())
    return;
  auto* vfs = runtime->file_system();
  HostPathDevice* game = GameDevice(vfs);
  if (!game) {
    RDAHM_ERROR("[mods] game: isn't a host folder; mods not loaded");
    return;
  }
  const std::string mount = game->mount_path();
  const fs::path game_root = game->host_path();
  const bool read_only = game->is_read_only();
  const bool share_delete = game->allow_share_delete();
  const fs::path mods_dir = ModsDir();

  // Game path -> file, later mods over earlier ones; the mods' roots, last
  // listed first.
  std::map<std::string, ModFile> files;
  std::vector<std::pair<std::string, fs::path>> roots;
  std::vector<ModSource> sources;
  std::vector<ModEntry*> used;
  for (ModEntry* entry : mods) {
    const std::string& mod = entry->name;
    const fs::path& dir = entry->dir;
    std::error_code error;
    if (!fs::is_directory(dir, error)) {
      RDAHM_WARN("[mods] '{}' not found in {}", mod, Utf8(mods_dir));
      continue;
    }
    const fs::path root = FindModRoot(dir);
    int patches = 0;
    const size_t before = files.size();
    CollectModFiles(mod, root, files, patches);
    RDAHM_INFO("[mods] '{}': {} files, {} .PackagePatch files", mod, files.size() - before, patches);
    roots.emplace(roots.begin(), mod, root);
    sources.push_back({mod, dir, root});
    used.push_back(entry);
  }
  if (roots.empty())
    return;

  // Packages the mods edit, built (or reused) in the generated folder, which
  // sits in front of every mod.
  const fs::path generated = mods_dir / std::string(kGeneratedFolder);
  std::map<std::string, BuiltFile> built;
  std::atomic<bool> done{false};
  std::thread builder([&] {
    built = BuildPackages(sources, game_root, generated);
    done = true;
  });
  while (!done) {
#if defined(_WIN32)
    MSG message;
    PeekMessageW(&message, nullptr, 0, 0, PM_NOREMOVE);
#endif
    std::this_thread::sleep_for(std::chrono::milliseconds(50));
  }
  builder.join();
  for (const auto& [key, file] : built)
    files[key] = ModFile{file.host, file.game_path, "(built)"};
  for (const auto& [key, file] : files)
    RDAHM_DEBUG("[mods] {} <- {}", file.game_path, file.mod);
  WriteToc(game_root, files, generated / fs::path(std::string(kTocPath)));

  // The overlay gets a mount of its own and game: and d: are pointed at it.
  // The VFS hands a path to the first device, in registration order, whose
  // mount path begins it, so a device registered again at the game's mount
  // would sit behind any device mounted on a shorter prefix of it. The game's
  // own device stays where it is.
  std::vector<std::unique_ptr<Device>> layers;
  layers.push_back(std::make_unique<HostPathDevice>(kOverlayMount, generated, true));
  for (const auto& [mod, root] : roots)
    layers.push_back(std::make_unique<HostPathDevice>(kOverlayMount, root, true));
  layers.push_back(
      std::make_unique<HostPathDevice>(kOverlayMount, game_root, read_only, share_delete));
  auto overlay = std::make_unique<OverlayDevice>(kOverlayMount, std::move(layers));
  if (!overlay->Initialize()) {
    RDAHM_ERROR("[mods] couldn't read the mod folders; mods not loaded");
    return;
  }
  vfs->RegisterDevice(std::move(overlay));
  int relinked = 0;
  for (std::string_view link : {"game:", "d:", "GAME:", "D:"}) {
    std::string target;
    if (vfs->FindSymbolicLink(link, target) && Lower(target) == Lower(mount)) {
      vfs->UnregisterSymbolicLink(link);
      vfs->RegisterSymbolicLink(link, kOverlayMount);
      ++relinked;
    }
  }
  if (!relinked) {
    RDAHM_ERROR("[mods] no game: link to {} found; mods not loaded", mount);
    vfs->UnregisterDevice(kOverlayMount);
    return;
  }
  RDAHM_INFO("[mods] {} mod(s) loaded over {} ({})", roots.size(), mount, game_root.string());
  for (ModEntry* entry : used)
    entry->mod.loaded = true;

  // The first file the title reads, read the way it reads it.
  File* toc = nullptr;
  rex::filesystem::FileAction action{};
  const X_STATUS status = vfs->OpenFile(
      nullptr, std::string("game:\\") + std::string(kTocPath),
      rex::filesystem::FileDisposition::kOpen, rex::filesystem::FileAccess::kGenericRead, false,
      true, &toc, &action);
  if (toc)
    toc->Destroy();
  else
    RDAHM_ERROR("[mods] the merged game folder doesn't open its TOC ({:08X})", uint32_t(status));
}

}  // namespace redahm::mods

// The title's dirty-disc error (sub_82E64750 -> XamShowDirtyDiscErrorUI):
// raised on any failed read, and with mods, often one of theirs. Logs where
// it was raised from.
REX_EXTERN(__imp__sub_82E64750);
REX_HOOK_RAW(sub_82E64750) {
  RDAHM_ERROR("[mods] the game reports a disc read error, from {}",
              redahm::crash::GuestCallChain());
  __imp__sub_82E64750(ctx, base);
}
